### PR TITLE
[ Fix ] Node v20 - Migrate to `base32Encode`.

### PR DESCRIPTION
**Pull request by kldeb**
Solves node v20 issue running on aws lambda

### CODE REVIEW

**Comment by dev-xo** [comment]
Thanks for the PR, @kldeb.

I noticed some indentation we do not have in the project. Not sure if you can run `npm run format` in order to fix that. Also, hopefully, @mw10013 could also take a look at the PR.

**Comment by kldeb** [comment]
strange, i did run the format script.

**Comment by dev-xo** [comment]
All right, nothing to worry about.

Not sure if we will need some small tests of the `base32Encode` or if we had those for `thirty-two`; in any case, let's wait for @mw10013 to share some thoughts, and we will probably merge it!

**Comment by dev-xo** [comment]
We will need to bump `@epic-web/totp` to the new version, right? Let us know what pending changes need to be made in order for us to also publish a new version of `remix-auth-totp`, @kldeb.

Also, thanks for the efforts and the improvements!

**Comment by mw10013** [comment]
@kldeb Thanks for the PR! Looks good from my side.

**Review by dev-xo — APPROVED** [review]

**Comment by dev-xo** [comment]
Merged and published. Let me know if everything works as expected, @kldeb. Again, thanks for the time spent and the efforts!

**Comment by kldeb** [comment]
@dev-xo thanks! Just tested it and it works!

**Comment by dev-xo** [comment]
Happy to hear that, @kldeb! Thanks for the PR. Feel free to suggest anything else or come up with some other features/improvements!

**Pull request merged**
