### PR TITLE
[ Feat ]: Phone Support

### PR DESCRIPTION
**Pull request by shawnmclean**
### Summary

Adding phone number support for whatsapp and sms TOTP verification.

### Notes

This is the first draft of the model changes for fast feedback.

### References

#49

### CODE REVIEW

**Comment by dev-xo** [comment]
Hello @shawnmclean,

Will share my thoughts after checking the implementation, but overall I would let @mw10013 make the final decision as he understands the whole authentication strategy better than me at this point.

Thank you for the PR.

**Comment by dev-xo** [comment]
Check the implementation @shawnmclean, looks good to me.

Any way we could have a phone number validator and the tests for the implementation?
- For me, this could be a merge if we are able to ensure a good way to validate phones (also expose that validation to the user in the same way we are exposing the email validation) and also add some tests.

https://github.com/dev-xo/remix-auth-totp/blob/d98d89fcd47e9ef27c36e08684c9fc843659a5d9/src/index.ts#L470-L473

**Comment by mw10013** [comment]
@shawnmclean: Thanks for the PR! I apologize for being a little late to the discussion. 

Can you outline your use case for this so I have a better understanding. `remix-auth-totp` is intended to authenticate email addresses by having the user prove they have access to the email sent out. If email and phone are specified, a user could specify a phone unrelated to the email and gain access to the account through an unauthenticated email.

**Comment by mw10013** [comment]
@shawnmclean: Thanks for clarifying. 

If I understand correctly, you are not trying to authenticate an email and phone number at the same time. And also not trying to authenticate an email with a phone number or vice-versa. You seem to want to authenticate either an email or a phone number.

Taking a step back, I'm wondering if you were able to authenticate a phone number alone using `remix-auth-totp` and configuring the regex and error messages to reflect a phone number instead of email. And in the `sendTOTP()`, you treat the `email` parameter as a phone number. Please share if you were able to achieve that or what experiements you have conducted in that area.

If that's the case, then I wonder if you are able to run two instances to `TOTP` in parallel. One for email and the other for phone. 

I'd probably lean more toward making `remix-auth-totp` more generic in the sense that it's simply authenticating a string. Currently, it treats the string as an email, but it could be agnostic about that.

Adding on another specialized string such as phone seems to lead to someone else wanting a different specialized string and so on. If `remix-auth-totp` were generic then the app could decide what specialized string it wanted to authenticate.

**Comment by chiptus** [comment]
@mw10013 I was also leaning toward just validating a string. for separation of concerns, I think phone and email (and whatsapp) should have separate config.

if we can use different startegies this might make it simpler. just need to remove the "email" word from the config.

how do we make remix auth use one startegy or the other?

**Comment by mw10013** [comment]
@chiptus: Apologies for delayed response. It would be helpful if you could share your specific use case, if you have one. For instance, I'm trying to authenticate email and phone. I tried running 2 instances of `remix-auth-totp` and these were the speed bumps and roadblocks.

Have you been able to use `remix-auth-totp` to authenticate a phone by changing options into `remix-auth` and `remix-auth-totp`? We'd love to have some field reports on what users have been able to accomplish in this area or where things fell short.

I believe `remix-auth` can handle running multiple strategies in parallel. And we would love to have some field reports running 2 instances of 'remix-auth-totp` in parallel.

**Comment by chiptus** [comment]
hey, currently we have only whatsapp verification. this is the code I use:
```
import type { User } from "@prisma/client";
import { isAxiosError } from "axios";
import { Authenticator } from "remix-auth";
import type { SendTOTPOptions, TOTPVerifyParams } from "remix-auth-totp";
import { TOTPStrategy } from "remix-auth-totp";
import { z } from "zod";

import { TOTP_ENCRYPTION_SECRET } from "~/utils/config.ts";
import { prisma } from "~/utils/prisma.server.ts";
import { sessionStorage } from "./session.server.ts";
// import { sendEmail } from './email.server'
import { sendWhatsapp } from "./totp.server.js";

export let authenticator = new Authenticator<User>(sessionStorage, {
  throwOnError: true,
});

authenticator.use(
  new TOTPStrategy(
    {
      
      secret: TOTP_ENCRYPTION_SECRET,
      totpGeneration: {
        charSet: "0123456789",
      },
      sendTOTP,
      emailFieldKey: "phone",
      validateEmail: async () => true,
    },
    verifyTOTP,
  ),
);

async function sendTOTP({ code, formData }: SendTOTPOptions): Promise<void> {
  try {
    const method = z
      .union([z.literal("email"), z.literal("whatsapp")])
      .parse(formData?.get("method") ?? "whatsapp");

    // Send the TOTP code to the user.
    if (method === "whatsapp") {
      let phone = z.string().parse(formData?.get("phone"));
      await sendWhatsapp(phone, code);
    }
  } catch (err) {
    if (!isAxiosError(err)) {
      // eslint-disable-next-line no-console
      console.error("sendTOTP", err);
      throw err;
    }
    throw new Error(err.response?.data?.message ?? err.message);
  }
}

async function verifyTOTP({
  formData,
  email: phone,
}: TOTPVerifyParams): Promise<User> {
  const method = z
    .union([z.literal("email"), z.literal("whatsapp")])
    .parse(formData?.get("method") ?? "whatsapp");

  if (method === "whatsapp") {
    let user = await prisma.user.findFirst({
      where: { phone },
    });

    if (!user) {
      user = await prisma.user.create({
        data: {
          phone,
          subscription: {
            create: {
              startDate: new Date(),
              status: "active",
              subscription: {
                connect: {
                  name: "Trial",
                },
              },
            },
          },
        },
      });
    }

    return user;
  }

  throw new Error("Invalid method");
}
```

I would like to add also email, and Product also wants to replace whatsapp with regular sms

**Comment by mw10013** [comment]
@chiptus: Thanks for sharing some code. It really helps to make things concrete.

`remix-auth` is designed to take multiple strategies and you can, for example, use two instance of `remix-auth-totp` and just give the second one a different name.

https://github.com/sergiodxa/remix-auth/blob/ab7aef1212680edc0642b3d14a64fdf2a250951b/src/authenticator.ts#L71-L83

  /**
   * Call this method with the Strategy, the optional name allows you to setup
   * the same strategy multiple times with different names.
   * It returns the Authenticator instance for concatenation.
   * @example
   * authenticator
   *  .use(new SomeStrategy({}, (user) => Promise.resolve(user)))
   *  .use(new SomeStrategy({}, (user) => Promise.resolve(user)), "another");
   */
  use(strategy: Strategy<User, never>, name?: string): Authenticator<User> {
    this.strategies.set(name ?? strategy.name, strategy);
    return this;
  }

Wondering if you can have 1 instance for email and the other for regular sms. If you do try this, please let us know how it goes and if you hit any obstacles. We'd love to see this working.

**Pull request closed without merging**
